aws_profile="default"
aws_region="ap-southeast-1"
stack="tf-ecs"
fargate-task-service-role="tf-ecs-role"
aws_ecr="petclinic"
source_repo_name="petclinic"
source_repo_branch="master"
image_repo_name="petclinic"